// Generated by CoffeeScript 1.4.0
(function() {
  var Client, EventEmitter, ws,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = require('events').EventEmitter;

  ws = require('ws');

  Client = (function(_super) {

    __extends(Client, _super);

    function Client(url, options) {
      this.url = url;
      this.options = options != null ? options : {};
      this.onMessage = __bind(this.onMessage, this);

      this.onError = __bind(this.onError, this);

      this.onClose = __bind(this.onClose, this);

      this.onOpen = __bind(this.onOpen, this);

      this.onConnect = __bind(this.onConnect, this);

      this.start = __bind(this.start, this);

      return this;
    }

    Client.prototype.start = function() {
      var href;
      console.log('Client: url->', this.url.format());
      href = this.url.format();
      this.ws = new ws(this.url.format());
      this.ws.on('open', this.onOpen);
      this.ws.on('close', this.onClose);
      this.ws.on('error', this.onError);
      this.ws.on('message', this.onMessage);
      this.ws.on('connect', this.onConnect);
    };

    Client.prototype.onConnect = function() {
      return console.log('onConnect');
    };

    Client.prototype.onOpen = function() {
      return console.log('onOpen');
    };

    Client.prototype.onClose = function() {
      return console.log('onClose');
    };

    Client.prototype.onError = function(err) {
      console.log('onError', err);
      return this.emit('error', err);
    };

    Client.prototype.onMessage = function() {
      return console.log('onMessage');
    };

    return Client;

  })(EventEmitter);

  module.exports = {
    Client: Client
  };

}).call(this);
