// Generated by CoffeeScript 1.4.0
(function() {
  var Client, io,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  io = require('socket.io-client');

  Client = (function() {

    function Client(url, options) {
      this.url = url;
      this.options = options != null ? options : {};
      this.start = __bind(this.start, this);

      return this;
    }

    Client.prototype.start = function() {
      console.log('Client: url->', this.url.format());
      this.io = io.connect(this.url.format());
      this.on = this.io.on;
      return this.emit = this.io.emit;
    };

    return Client;

  })();

  module.exports = {
    Client: Client
  };

}).call(this);
