// Generated by CoffeeScript 1.4.0
(function() {
  var Shell, readline,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  readline = require('readline');

  Shell = (function() {

    function Shell(options) {
      var _base, _base1, _ref, _ref1;
      this.options = options != null ? options : {};
      this.exit = __bind(this.exit, this);

      this.start = __bind(this.start, this);

      if ((_ref = (_base = this.options).input) == null) {
        _base.input = process.stdin;
      }
      if ((_ref1 = (_base1 = this.options).output) == null) {
        _base1.output = process.stdout;
      }
      return this;
    }

    Shell.prototype.start = function() {
      this.rl = readline.createInterface(this.options);
      this.on = this.rl.on;
      return this.emit = this.rl.emit;
    };

    Shell.prototype.exit = function(code) {
      console.log('Shell.exit:', code);
      return process.exit(code);
    };

    return Shell;

  })();

  module.exports = {
    Shell: Shell
  };

}).call(this);
