// Generated by CoffeeScript 1.4.0
(function() {
  var Shell, readline;

  readline = require('readline');

  Shell = (function() {

    function Shell(options) {
      var _base, _base1, _ref, _ref1;
      this.options = options != null ? options : {};
      if ((_ref = (_base = this.options).input) == null) {
        _base.input = process.stdin;
      }
      if ((_ref1 = (_base1 = this.options).output) == null) {
        _base1.output = process.stdout;
      }
      return this;
    }

    Shell.prototype.start = function() {
      return this.rl = readline.createInterface(this.options);
    };

    return Shell;

  })();

  module.exports = {
    Shell: Shell
  };

}).call(this);
