// Generated by CoffeeScript 1.4.0
(function() {
  var Base, WSClient, ws,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require('./Base').Base;

  ws = require('ws');

  WSClient = (function(_super) {

    __extends(WSClient, _super);

    function WSClient(url, options) {
      this.url = url;
      this.options = options != null ? options : {};
      this.onMessage = __bind(this.onMessage, this);

      this.onError = __bind(this.onError, this);

      this.onClose = __bind(this.onClose, this);

      this.onOpen = __bind(this.onOpen, this);

      this.onConnect = __bind(this.onConnect, this);

      this.end = __bind(this.end, this);

      this.send = __bind(this.send, this);

      this.start = __bind(this.start, this);

      return this;
    }

    WSClient.prototype.start = function() {
      var href;
      this.log('WSClient: url->', this.url.format());
      href = this.url.format();
      this.ws = new ws(this.url.format());
      this.ws.on('open', this.onOpen);
      this.ws.on('close', this.onClose);
      this.ws.on('error', this.onError);
      this.ws.on('message', this.onMessage);
      return this.ws.on('connect', this.onConnect);
    };

    WSClient.prototype.send = function(d) {
      this.log('WSClient.send', d);
      return this.ws.send(d);
    };

    WSClient.prototype.end = function() {
      this.log('WSClient.end');
      return this.ws.close();
    };

    WSClient.prototype.onConnect = function() {
      this.log('WSClient.onConnect');
      return this.emit('connect');
    };

    WSClient.prototype.onOpen = function() {
      this.log('WSClient.onOpen');
      return this.emit('open');
    };

    WSClient.prototype.onClose = function() {
      this.log('WSClient.onClose');
      return this.emit('close');
    };

    WSClient.prototype.onError = function(err) {
      this.log('WSClient.onError', err);
      return this.emit('error', err);
    };

    WSClient.prototype.onMessage = function(msg) {
      this.log('WSClient.onMessage', msg);
      return this.emit('message', msg);
    };

    return WSClient;

  })(Base);

  module.exports = {
    WSClient: WSClient
  };

}).call(this);
